### ISSUE TITLE
Failing on chaste patch

### ISSUE THREAD

**Issue by kephale** [mobernabeu/homebrew-chaste#1]
Hi Miguel,

This is the specific error that I get (running Mavericks):

==> Verifying chaste--patch-faa28dcb345cd20f1086b24ea23122dd668b57e0.diff checksum
==> Patching
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/chaste--patch-X6vfzU/macosx.diff
patching file python/hostconfig/macosx.py
Hunk #1 FAILED at 1.
1 out of 3 hunks FAILED -- saving rejects to file python/hostconfig/macosx.py.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/chaste--patch-X6vfzU/macosx.diff
ADA424B2:~ kharrin3$ /usr/bin/patch -g 0 -f -p1 -i /private/tmp/chaste--patch-X6vfzU/macosx.diff
/usr/bin/patch: ***\* Can't open patch file /private/tmp/chaste--patch-X6vfzU/macosx.diff : No such file or directory

Thanks,
Kyle

**Comment by mobernabeu** [comment]
Thanks for reporting the issue @kephale and apologies for the slow reply. 

I've updated the patch following some Chaste changes upstream. Could you please try again (remember to `brew update` first) and see whether the issue is gone on your end?

**Comment by kephale** [comment]
Still not working, but new error:
==> Installing chaste
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Cloning https://github.com/chaste/chaste.git
Updating /Library/Caches/Homebrew/chaste--git
==> Checking out branch master
==> Downloading https://raw.githubusercontent.com/mobernabeu/homebrew-chaste/master/macosx.diff
######################################################################## 100.0%
==> Patching
patching file python/hostconfig/macosx.py
==> scons cl=1 co=1 cell_based -j4
    return 0xUINT_MAX;
            ^
1 error generated.
scons: **\* [global/build/debug/src/Version.os] Error 1
scons: building terminated because of errors.

**Comment by mobernabeu** [comment]
This seems to be a compilation error in Chaste itself. I can reproduce it locally. I'll get in touch with them and see what they say.

**Comment by mobernabeu** [comment]
@kephale: The Chaste bug that you reported has been fixed upstream. Could you please try again?

**Comment by kephale** [comment]
Thanks. It looks like it builds, and I'll try linking against it today but I get this error:

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /usr/local/Cellar/chaste/HEAD/include/chaste/cell_based/build/debug/simulation/TestOnLatticeSimulationWithPdesRunner (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
Error: Failed to fix install names
The formula built, but you may encounter issues using it or linking other
formula against it.

**Comment by mobernabeu** [comment]
I saw that error earlier today and I'm investigating what it may mean. 

I have however been able to link Kate's code against Chaste, so please ignore the error and try linking on your end.

**Comment by mobernabeu** [comment]
The original error in this issue has been addressed. I've created #5 to investigate the latest problem reported by @kephale, which doesn't seem to prevent the installation from completing. Closing.
